// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC4j13WDdS3D7oVpA74MIBK_pP8JdeT9w',
    appId: '1:1098978582484:web:6a34673a04488e717ec041',
    messagingSenderId: '1098978582484',
    projectId: 'authtest-ac700',
    authDomain: 'authtest-ac700.firebaseapp.com',
    storageBucket: 'authtest-ac700.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsgEYI4Edn9xfdMp2a7cyUw0b-CIcvKE',
    appId: '1:1098978582484:android:f57a8ad464e971857ec041',
    messagingSenderId: '1098978582484',
    projectId: 'authtest-ac700',
    storageBucket: 'authtest-ac700.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC4j13WDdS3D7oVpA74MIBK_pP8JdeT9w',
    appId: '1:1098978582484:web:ba019608ecaab0c97ec041',
    messagingSenderId: '1098978582484',
    projectId: 'authtest-ac700',
    authDomain: 'authtest-ac700.firebaseapp.com',
    storageBucket: 'authtest-ac700.firebasestorage.app',
  );
}
